[package]
name = "strategy_lib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.99"
serde_json = "1.0.143"
farukon_core = { path = "../farukon_core" }
chrono = { version = "0.4.41", features = ["serde"] }
