// farukon_core/src/settings.rs

//! Configuration structures for the Farukon platform.
//! Loads settings from JSON files and validates them.

use crate::commission_plans;

/// Represents a parameter specification that can be either a discrete list of values or a continuous range.
/// 
/// This enum allows flexible definition of parameter spaces for optimization algorithms.
/// It supports both explicit value lists and range-based definitions with step increments.
/// 
/// # Variants
/// * `Discrete(Vec<Value>)` - A fixed list of specific parameter values (e.g., [1.0, 2.0, 3.0])
/// * `Range { start, end, step }` - A continuous range of values from `start` to `end` with given `step` (e.g., 1.0 to 5.0 with step 0.5)
/// 
/// # Usage
/// 
/// JSON configurations that can be deserialized into `ParamSpec`:
/// 
/// ```json
/// // Discrete values
/// "param": [1.0, 2.0, 3.0]
/// 
/// // Range specification
/// "param": {"start": 1.0, "end": 10.0, "step": 0.5}
/// ```
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(untagged)]
pub enum ParamSpec {
    Discrete(Vec<serde_json::Value>),
    Range {
        start: f64,
        end: f64,
        step: f64,
    },
}

impl ParamSpec {
    /// Expands the parameter specification into a full vector of values.
    /// 
    /// For `Discrete`, returns the stored vector. For `Range`, generates all values
    /// from `start` to `end` inclusive with the given `step`.
    /// 
    /// # Returns
    /// A vector of `serde_json::Value` containing all possible parameter values.
    pub fn expand(&self) -> Vec<serde_json::Value> {
        match self {
            ParamSpec::Discrete(values) => values.clone(),
            ParamSpec::Range { start, end, step } => {
                let mut values = Vec::new();
                let mut current = *start;
                while current <= *end + std::f64::EPSILON {
                    values.push(serde_json::Value::Number(
                        serde_json::Number::from_f64(current).expect("Valid f64")
                    ));
                    current += *step;
                }
                values
            }
        }
    }

    /// Returns the minimum and maximum bounds of the parameter range.
    /// 
    /// For `Discrete`, calculates min/max from the values. For `Range`, returns (start, end).
    /// 
    /// # Returns
    /// A tuple `(min, max)` representing the parameter bounds.
    pub fn range_bounds(&self) -> (f64, f64) {
        match self {
            ParamSpec::Discrete(values) => {
                let nums: Vec<f64> = values
                    .iter()
                    .filter_map(|v| v.as_f64())
                    .collect();
                if nums.is_empty() {
                    (0.0, 0.0)
                } else {
                    let min = *nums.iter().min_by(|a, b| a.partial_cmp(&b).unwrap_or(std::cmp::Ordering::Equal)).unwrap();
                    let max = *nums.iter().max_by(|a, b| a.partial_cmp(&b).unwrap_or(std::cmp::Ordering::Equal)).unwrap();
                    (min, max)
                }
            }
            ParamSpec::Range { start, end, .. } => (*start, *end),
        }
    }

    /// Returns the step size for range-based parameters.
    /// 
    /// # Returns
    /// `Some(step)` for `Range`, `None` for `Discrete`.
    pub fn step(&self) -> Option<f64> {
        match self {
            ParamSpec::Discrete(_) => None,
            ParamSpec::Range { step, .. } => Some(*step),
        }
    }

    /// Calculates the number of values that would be generated by `expand()`.
    /// 
    /// This is useful for memory estimation and avoiding combinatorial explosions.
    /// 
    /// # Returns
    /// The count of values in the expanded parameter space.
    pub fn count_expanded_values(&self) -> usize {
        match self {
            ParamSpec::Discrete(values) => values.len(),
            ParamSpec::Range { start, end, step } => {
                (((end - start) / step).floor() as usize) + 1
            }
        }
    }

}

/// Type of optimizer to use.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub enum OptimizerType {
    #[serde(rename = "Grid_Search")]
    GridSearch,
    #[serde(rename = "Genetic")]
    Genetic { ga_params: GAParams },
}

/// Type of fitness metric to optimize.
#[derive(serde::Deserialize, serde::Serialize, Debug, Clone)]
#[serde(deny_unknown_fields)]
pub enum FitnessValue {
    #[serde(rename = "Total_Return")]
    TotalReturn,
    #[serde(rename = "Total_Return_%")]
    TotalReturnPercent,
    #[serde(rename = "APR")]
    APR,
    #[serde(rename = "Max_Drawdown")]
    MaxDD,
    #[serde(rename = "APR/DD_factor")]
    AprDDFactor,
    #[serde(rename = "Recovery_Factor")]
    RecoveryFactor,
    #[serde(rename = "Deals_Count")]
    DealsCount,
    #[serde(rename = "Composite")]
    Composite { metrics: Vec<String> },
}

impl Default for FitnessValue {
    fn default() -> Self {
        FitnessValue::AprDDFactor
    }
}

/// Parameters for the Genetic Algorithm optimizer.
#[derive(serde::Deserialize, serde::Serialize, Debug, Clone)]
#[serde(deny_unknown_fields)]
pub struct GAParams {
    pub population_size: usize,
    pub p_crossover: f64,
    pub p_mutation: f64,
    pub max_generations: usize,
    pub fitness_params: FitnessParams,
}

/// Fitness function parameters for the Genetic Algorithm.
#[derive(serde::Deserialize, serde::Serialize, Debug, Clone)]
#[serde(deny_unknown_fields)]
pub struct FitnessParams {
    pub fitness_direction: String,
    pub fitness_value: FitnessValue,
}

#[derive(serde::Deserialize, serde::Serialize, Debug, Clone)]
#[serde(deny_unknown_fields)]
pub struct MarginParams {
    pub min_margin: f64,
    pub margin_call_type: String,
}

/// Position sizing parameters.
#[derive(serde::Deserialize, serde::Serialize, Debug, Clone)]
#[serde(deny_unknown_fields)]
pub struct PosSizer {
    pub pos_sizer_name: String,
    pub pos_sizer_params: std::collections::HashMap<String, ParamSpec>,
    pub pos_sizer_value: ParamSpec,
}

/// Data settings for a strategy.
#[derive(serde::Deserialize, serde::Serialize, Debug, Clone)]
#[serde(deny_unknown_fields)]
pub struct DataSettings {
    pub data_path: String,
    pub timeframe: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub enum KellyMode {
    #[serde(rename = "on")]
    On,
    #[serde(rename = "off")]
    Off,
}

/// Mode for calculating performance metrics.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub enum MetricsMode {
    #[serde(rename = "offline")]
    Offline,
    #[serde(rename = "realtime")]
    RealTime { modified_kelly_creterion: KellyMode },
}

/// Portfolio settings for a strategy.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PortfolioSettingsForStrategy {
    pub metrics_calculation_mode: MetricsMode,
}

/// Settings for a single strategy.
#[derive(serde::Deserialize, serde::Serialize, Debug, Clone)]
#[serde(deny_unknown_fields)]
pub struct StrategySettings {
    pub threads: Option<usize>,
    pub strategy_name: String,
    pub strategy_path: String,
    pub exit_results_path: String,
    pub strategy_weight: f64,
    pub slippage: ParamSpec,
    pub data: DataSettings,
    pub symbols: Vec<String>,
    pub strategy_params: std::collections::HashMap<String, ParamSpec>,
    pub pos_sizer_params: PosSizer,
    pub margin_params: MarginParams,
    pub portfolio_settings_for_strategy: PortfolioSettingsForStrategy,
    pub optimizer_type: OptimizerType,
    #[serde(skip_deserializing)]
    pub commission_plans: Option<commission_plans::CommissionPlans>
}

/// Common settings applicable to the entire platform.
#[derive(serde::Deserialize, serde::Serialize, Debug, Clone)]
#[serde(deny_unknown_fields)]
pub struct CommonSettings {
    pub mode: String,
    pub initial_capital: f64,
    pub commission_plans_path: String,
    pub instrument_info_path: String,
    pub global_data_storage_mode: String,
}

/// Top-level settings structure.
#[derive(serde::Deserialize, serde::Serialize, Debug, Clone)]
#[serde(deny_unknown_fields)]
pub struct Settings {
    pub common: CommonSettings,
    pub portfolio: std::collections::HashMap<String, StrategySettings>,
}

impl Settings {
    /// Loads settings from a JSON file.
    /// # Arguments
    /// * `config_path` - Path to the JSON configuration file.
    /// * `instruments_info` - Instrument metadata registry.
    /// # Returns
    /// * `anyhow::Result<Settings>` containing the loaded settings.
    pub fn load<P: AsRef<std::path::Path>>(
        settings_file_path: P,
        // instruments_info: &instruments_info::InstrumentsInfoRegistry,
    ) -> anyhow::Result<Self> {
        let contents = std::fs::read_to_string(settings_file_path)?;
        let mut settings: Settings = serde_json::from_str(&contents)
            .map_err(|e| anyhow::anyhow!("Failed to parse settings JSON: {}", e))?;

        check_args(&mut settings)
            .map_err(|e| anyhow::anyhow!("Settings validation failed:\n{}", e))?;

        anyhow::Ok(settings)
    }

}

fn check_args(
    settings: &mut Settings
) -> anyhow::Result<()> {
    // check threads
    {
        let strategies_ids: Vec<String> = settings.portfolio.keys().cloned().collect();
        for strategy_id in strategies_ids {
            let strategy_settings: &mut StrategySettings = settings.portfolio.get_mut(&strategy_id).unwrap();
            match strategy_settings.threads {
                Some(threads) => {
                    if threads == 0 {
                        anyhow::bail!("Settings validation error: 'threads' cannot be zero.");
                    } else if threads > 0 {
                        let availiable_threads = num_cpus::get();
                        if threads > availiable_threads {
                            strategy_settings.threads = Some(availiable_threads);
                        }
                    }
                },
                None => {}
            }
        }
    }

    // check mode
    {
        const VALID_MODES: &[&str] = &["Debug", "Optimize", "Visual"];
        if !VALID_MODES.contains(&settings.common.mode.as_str()) {
            anyhow::bail!("Wrong mode setting! Use one of {:?}", VALID_MODES);
        }

        const VALID_DATA_MODES: &[&str] = &["arc", "deep"];
        if !VALID_DATA_MODES.contains(&settings.common.global_data_storage_mode.as_str()) {
            anyhow::bail!("Wrong global data mode setting! Use one of {:?}", VALID_DATA_MODES);
        }
    }

    // check portfolio
    {
        let strategies = settings.portfolio.keys();
        for strategy in strategies {
            let strategy_settings = settings.portfolio.get(strategy).unwrap();

            // check optimizer type
            {
                match &strategy_settings.optimizer_type {
                    OptimizerType::Genetic { ga_params }=> {
                        if ga_params.population_size == 0 {
                            anyhow::bail!("GA population_size must be greater than 0");
                        }
                        if ga_params.p_crossover < 0.0 || ga_params.p_crossover > 1.0 {
                            anyhow::bail!("GA p_crossover must be between 0.0 and 1.0");
                        }
                        if ga_params.p_mutation < 0.0 || ga_params.p_mutation > 1.0 {
                            anyhow::bail!("GA p_mutation must be between 0.0 and 1.0");
                        }
                        if ga_params.max_generations == 0 {
                            anyhow::bail!("GA max_generations must be greater than 0");
                        }

                        // check fitness_direction
                        let dir_str = &ga_params.fitness_params.fitness_direction;
                        if dir_str != "max" && dir_str != "min" {
                            anyhow::bail!("fitness_direction must be 'max' or 'min'");
                        }

                        // check fitness_value
                        match &ga_params.fitness_params.fitness_value {
                            FitnessValue::Composite { metrics } => {
                                const VALID_COMPOSITE_METRICS: &[&str] = &[
                                    "Total_Return",
                                    "Total_Return_%",
                                    "APR",
                                    "max_DD", 
                                    "max_DD_%",
                                    "APR/DD_factor",
                                    "Recovery_Factor",
                                    "Recovery_Factor_%",
                                    "Deals_Count",
                                ];

                                if metrics.is_empty() {
                                    anyhow::bail!(
                                        "Composite fitness must have at least one metric. One of {:?}",
                                        VALID_COMPOSITE_METRICS
                                    );
                                }

                                for metric in metrics {
                                    if !VALID_COMPOSITE_METRICS.contains(&metric.as_str()) {
                                        anyhow::bail!(
                                            "Invalid composite metric '{}'. Must be one of: {:?}",
                                            metric,
                                            VALID_COMPOSITE_METRICS
                                        );
                                    }
                                }
                            },
                            _ => {}
                        }
                    },
                    OptimizerType::GridSearch => {}
                }
            }

            // check timeframe
            {
                const VALID_TIMEFRAMES: &[&str] = &["1min", "2min", "3min", "4min", "5min", "1d"];
                if !VALID_TIMEFRAMES.contains(&strategy_settings.data.timeframe.as_str()) {
                    anyhow::bail!("Wrong mode setting! Use one of {:?}", VALID_TIMEFRAMES);
                }
            }

            // check symbols
            {
                if strategy_settings.symbols.is_empty() {
                    anyhow::bail!("Provide symbol list!")
                }
            }

            // check pos sizers
            {
                const VALID_POS_SIZERS: &[&str] = &["mpr", "poe", "fixed_ratio", "1"];
                if !VALID_POS_SIZERS.contains(&strategy_settings.pos_sizer_params.pos_sizer_name.as_str()) {
                    anyhow::bail!("Wrong pos sizer. Use one of: {:#?}", VALID_POS_SIZERS);
                }

                if &strategy_settings.pos_sizer_params.pos_sizer_name == "1" {
                    match &strategy_settings.pos_sizer_params.pos_sizer_value {
                        ParamSpec::Discrete(values) => {
                            if !values.is_empty() {
                                anyhow::bail!("Pos sizer value vector of plain '1' param must be empty!");
                            }
                        }
                        ParamSpec::Range { start, end, .. } => {
                            if *start != *end {
                                anyhow::bail!("Pos sizer value for '1' must be a single value (start == end)!");
                            }
                        }
                    }
                } else {
                    match &strategy_settings.pos_sizer_params.pos_sizer_value {
                        ParamSpec::Discrete(values) => {
                            if !values.is_empty() {
                                anyhow::bail!("Pos sizer value vector of plain '1' param must be empty!");
                            }
                            for value in values {
                                if let Some(num) = value.as_f64() {
                                    if num < 0.0 {
                                        anyhow::bail!("Pos sizer values must be positive!")
                                    }
                                }
                            }
                        }
                        ParamSpec::Range { start, end, step } => {
                            if *start <= 0.0 || *end <= 0.0 {
                                anyhow::bail!("Pos sizer values must have positive values!");
                            }
                            if *start > *end {
                                anyhow::bail!("Pos sizer values: start > end!");
                            }
                            if *step <= 0.0 {
                                anyhow::bail!("Pos sizer values: step must be positive!");
                            }
                        }
                    }
                }
            }

            // check slippage vector
            {
                match &strategy_settings.slippage {
                    ParamSpec::Discrete(values) => {
                        if values.is_empty() {
                            anyhow::bail!("Slippage vector cannot be empty!");
                        }
                        for value in values {
                            if let Some(num) = value.as_f64() {
                                if num < 0.0 {
                                    anyhow::bail!("Slipage values must be positive!")
                                }
                            }
                        }
                    }
                    ParamSpec::Range { start, end, step } => {
                        if *start <= 0.0 || *end <= 0.0 {
                            anyhow::bail!("Slippage range must have positive values!");
                        }
                        if *start > *end {
                            anyhow::bail!("Slippage range: start > end!");
                        }
                        if *step <= 0.0 {
                            anyhow::bail!("Slippage range: step must be positive!");
                        }
                    }
                }
            }

            // check strategy params range
            {
                for (param_name, spec) in &strategy_settings.strategy_params {
                    match spec {
                        ParamSpec::Discrete(values) => {
                            if values.is_empty() {
                                anyhow::bail!("Strategy parameter '{}' discrete list cannot be empty!", param_name);
                            }
                            for value in values {
                                if let Some(num) = value.as_f64() {
                                    if num <= 0.0 {
                                        anyhow::bail!("Strategy parameter '{}' must have positive values!", param_name);
                                    }
                                } else if let Some(num) = value.as_i64() {
                                    if num <= 0 {
                                        anyhow::bail!("Strategy parameter '{}' must have positive values!", param_name);
                                    }
                                }
                            }
                        }
                        ParamSpec::Range { start, end, step } => {
                            if *start <= 0.0 || *end <= 0.0 {
                                anyhow::bail!("Strategy parameter '{}' range must have positive values!", param_name);
                            }
                            if *start > *end {
                                anyhow::bail!("In parameter '{}': start > end!", param_name);
                            }
                            if *step <= 0.0 {
                                anyhow::bail!("In parameter '{}': step must be positive!", param_name);
                            }
                        }
                    }

                }
            }

            // check exit path of results
            {
                let normalized_path = strategy_settings.exit_results_path
                    .trim_end_matches('/');

                if normalized_path.is_empty() {
                    anyhow::bail!("Exit path cannot be empty!")
                }

                let path = std::path::Path::new(normalized_path);
                if !path.exists() {
                    std::fs::create_dir_all(path)?;
                } else if !path.is_dir() {
                    anyhow::bail!("Exit path is not a directory!")
                }
            }
        }
    }

    anyhow::Ok(())
}
